import type { RecipeInput } from '../types/recipe'

export const dummyRecipes: RecipeInput[] = [
  {
    title: '김치볶음밥',
    description: '잘 익은 김치와 밥으로 빠르게 만드는 집밥 대표 메뉴.',
    image_url: '',
    ingredients: ['밥 1공기', '익은 김치 1컵', '대파 1/2대', '계란 1개'],
    seasonings: ['간장 1작은술', '참기름 1작은술', '고춧가루 1작은술'],
    steps: ['대파와 김치를 잘게 썬다.', '팬에 대파를 볶아 향을 낸다.', '김치와 밥을 넣고 볶은 뒤 간을 맞춘다.', '계란 프라이를 올린다.'],
    cooking_time: '15분',
    servings: 1,
    difficulty: '쉬움',
    tips: ['김치 국물을 조금 넣으면 맛이 진해진다.'],
    tags: ['한식', '간단요리', '집밥'],
    personal_note: '김치를 충분히 볶아야 신맛이 부드러워진다.',
    next_time_note: '',
    source_url: '',
    source_type: 'manual',
    youtube_video_id: '',
    is_favorite: true,
  },
  {
    title: '간장계란밥',
    description: '바쁜 아침에 좋은 고소한 한 그릇.',
    image_url: '',
    ingredients: ['밥 1공기', '계란 2개', '쪽파 약간'],
    seasonings: ['간장 1큰술', '참기름 1큰술', '깨 약간'],
    steps: ['따뜻한 밥을 그릇에 담는다.', '반숙 계란 프라이를 만든다.', '밥 위에 계란과 양념을 올려 섞는다.'],
    cooking_time: '8분',
    servings: 1,
    difficulty: '쉬움',
    tips: ['간장은 처음부터 많이 넣지 말고 조금씩 추가한다.'],
    tags: ['초간단', '아침', '계란'],
    personal_note: '참기름은 마지막에 넣어야 향이 좋다.',
    next_time_note: '',
    source_url: '',
    source_type: 'manual',
    youtube_video_id: '',
    is_favorite: false,
  },
  {
    title: '닭가슴살 샐러드',
    description: '담백한 닭가슴살과 채소를 곁들인 가벼운 식사.',
    image_url: '',
    ingredients: ['닭가슴살 1팩', '샐러드 채소 2줌', '방울토마토 6개', '오이 1/3개'],
    seasonings: ['올리브오일 1큰술', '레몬즙 1큰술', '소금 약간', '후추 약간'],
    steps: ['닭가슴살을 데우거나 구워 먹기 좋게 찢는다.', '채소를 씻어 물기를 제거한다.', '재료를 담고 드레싱을 뿌린다.'],
    cooking_time: '12분',
    servings: 1,
    difficulty: '쉬움',
    tips: ['닭가슴살은 너무 오래 익히면 퍽퍽해진다.'],
    tags: ['다이어트', '샐러드', '고단백'],
    personal_note: '레몬즙을 넉넉히 넣으면 산뜻하다.',
    next_time_note: '',
    source_url: '',
    source_type: 'manual',
    youtube_video_id: '',
    is_favorite: false,
  },
]
