-- Security hardening for profile privileges, API abuse controls, and payload bounds.

drop policy if exists "profiles_insert_own" on public.profiles;
revoke insert on public.profiles from anon, authenticated;
revoke update on public.profiles from anon, authenticated;
grant update (display_name) on public.profiles to authenticated;

update public.recipes
set ingredients = coalesce(ingredients, '[]'::jsonb),
    seasonings = coalesce(seasonings, '[]'::jsonb),
    step_images = coalesce(step_images, '[]'::jsonb),
    step_image_paths = coalesce(step_image_paths, '[]'::jsonb)
where ingredients is null
   or seasonings is null
   or step_images is null
   or step_image_paths is null;

alter table public.recipes
alter column ingredients set not null,
alter column seasonings set not null,
alter column step_images set not null,
alter column step_image_paths set not null;

alter table public.recipes
drop constraint if exists recipes_payload_bounds_check;

alter table public.recipes
add constraint recipes_payload_bounds_check check (
  jsonb_typeof(ingredients) = 'array'
  and jsonb_array_length(ingredients) <= 100
  and octet_length(ingredients::text) <= 100000
  and jsonb_typeof(seasonings) = 'array'
  and jsonb_array_length(seasonings) <= 100
  and octet_length(seasonings::text) <= 100000
  and jsonb_typeof(step_images) = 'array'
  and jsonb_array_length(step_images) <= 100
  and octet_length(step_images::text) <= 250000
  and jsonb_typeof(step_image_paths) = 'array'
  and jsonb_array_length(step_image_paths) <= 100
  and octet_length(step_image_paths::text) <= 250000
  and char_length(coalesce(image_url, '')) <= 2000
  and char_length(coalesce(image_path, '')) <= 1000
  and char_length(coalesce(source_url, '')) <= 2000
) not valid;

alter table public.recipes validate constraint recipes_payload_bounds_check;

update public.profiles
set display_name = nullif(left(trim(display_name), 100), '')
where display_name is distinct from nullif(left(trim(display_name), 100), '');

alter table public.profiles
drop constraint if exists profiles_display_name_check;

alter table public.profiles
add constraint profiles_display_name_check
check (display_name is null or char_length(trim(display_name)) between 1 and 100) not valid;

alter table public.profiles validate constraint profiles_display_name_check;

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    nullif(left(trim(new.raw_user_meta_data ->> 'display_name'), 100), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer set search_path = '';

create table if not exists public.api_request_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  action text not null,
  created_at timestamptz not null default now(),
  constraint api_request_usage_action_check
    check (action in ('image_sign', 'image_upload', 'image_delete'))
);

create index if not exists api_request_usage_user_action_created_idx
on public.api_request_usage (user_id, action, created_at desc);

alter table public.api_request_usage enable row level security;
revoke all on public.api_request_usage from public, anon, authenticated;

create or replace function public.consume_api_quota(
  p_user_id uuid,
  p_action text,
  p_window_seconds integer,
  p_limit integer
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_count integer;
begin
  if p_user_id is null
    or p_action not in ('image_sign', 'image_upload', 'image_delete')
    or p_window_seconds < 60
    or p_window_seconds > 86400
    or p_limit < 1
    or p_limit > 10000
  then
    return 'invalid';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_action, 0));

  delete from public.api_request_usage
  where user_id = p_user_id
    and created_at < now() - interval '7 days';

  select count(*)
    into request_count
  from public.api_request_usage
  where user_id = p_user_id
    and action = p_action
    and created_at >= now() - (p_window_seconds * interval '1 second');

  if request_count >= p_limit then
    return 'limit';
  end if;

  insert into public.api_request_usage (user_id, action)
  values (p_user_id, p_action);

  return 'ok';
end;
$$;

revoke all on function public.consume_api_quota(uuid, text, integer, integer)
from public, anon, authenticated;
grant execute on function public.consume_api_quota(uuid, text, integer, integer)
to service_role;

notify pgrst, 'reload schema';
